const library = [
    { 
        name: "Árvore da Vida", 
        attack: 0, 
        defense: 0, 
        cost: 9, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "druida", 
        collection: "gvg",
        image: "arvoredavida"
    },
    { 
        name: "Reciclar", 
        attack: 0, 
        defense: 0, 
        cost: 6, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "druida", 
        collection: "gvg",
        image: "reciclar"
    },
    { 
        name: "Malorne", 
        attack: 9, 
        defense: 7, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "fera", 
        hability: "ultimo suspiro", 
        class: "druida", 
        collection: "gvg",
        image: "malorne"
    },
    { 
        name: "Mecano-Urso-Felino", 
        attack: 7, 
        defense: 6, 
        cost: 6, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "peca sobressalente", 
        class: "druida", 
        collection: "gvg",
        image: "mecanoursofelino"
    },
    { 
        name: "Mantenedora do Bosque", 
        attack: 2, 
        defense: 4, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "escolha um", 
        class: "druida", 
        collection: "gvg",
        image: "mantenedoradobosque"
    },
    { 
        name: "Druida da Presa", 
        attack: 4, 
        defense: 4, 
        cost: 5, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "druida", 
        collection: "gvg",
        image: "druidadapresa"
    },
    { 
        name: "Fogo Enfático", 
        attack: 0, 
        defense: 0, 
        cost: 6, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "escolha um provocar", 
        class: "druida", 
        collection: "gvg",
        image: "fogoenfatico"
    },
    { 
        name: "Robozinho Anodizado", 
        attack: 2, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "provocar escolha um", 
        class: "druida", 
        collection: "gvg",
        image: "robozinhoanodizado"
    },
    { 
        name: "Atirador Bondebico", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "cacador", 
        collection: "gvg",
        image: "atiradorbondebico"
    },
    { 
        name: "Saltador Metalodonte", 
        attack: 3, 
        defense: 3, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "grito de guerra", 
        class: "cacador", 
        collection: "gvg",
        image: "saltadormetalodonte"
    },
    { 
        name: "Rei das Feras", 
        attack: 2, 
        defense: 6, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "fera", 
        hability: "provocar grito de guerra", 
        class: "cacador", 
        collection: "gvg",
        image: "reidasferas"
    },
    { 
        name: "Glaivezuca", 
        attack: 2, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "arma", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "cacador", 
        collection: "gvg",
        image: "glaivezuca"
    },
    { 
        name: "Gahz'rilla", 
        attack: 6, 
        defense: 9, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "fera", 
        hability: "nenhum", 
        class: "cacador", 
        collection: "gvg",
        image: "gahzrilla"
    },
    { 
        name: "Fingir de Morto", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "ultimo suspiro", 
        class: "cacador", 
        collection: "gvg",
        image: "fingirdemorto"
    },
    { 
        name: "Disparo da Naja", 
        attack: 0, 
        defense: 0, 
        cost: 5, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "cacador", 
        collection: "gvg",
        image: "disparodanaja"
    },
    { 
        name: "Chamar Ajudante", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "cacador", 
        collection: "gvg",
        image: "chamarajudante"
    },
    { 
        name: "Interrompe-feitiços Nanico", 
        attack: 2, 
        defense: 5, 
        cost: 4, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "mago", 
        collection: "gvg",
        image: "interrompefeiticosnanico"
    },
    { 
        name: "Portal Instável", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "mago", 
        collection: "gvg",
        image: "portalinstavel"
    },
    { 
        name: "Cospe-Fuligem", 
        attack: 3, 
        defense: 3, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "dano magico", 
        class: "mago", 
        collection: "gvg",
        image: "cospefuligem"
    },
    { 
        name: "Rompe-neve", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "congele", 
        class: "mago", 
        collection: "gvg",
        image: "rompeneve"
    },
    { 
        name: "Mago Explosivo Goblin", 
        attack: 5, 
        defense: 4, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "mago", 
        collection: "gvg",
        image: "magoexplosivogoblin"
    },
    { 
        name: "Canhão de Chamas", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "mago", 
        collection: "gvg",
        image: "canhaodechamas"
    },
    { 
        name: "Leviatã Flamejante", 
        attack: 7, 
        defense: 7, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "mago", 
        collection: "gvg",
        image: "leviataflamejante"
    },
    { 
        name: "Eco de Medivh", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "mago", 
        collection: "gvg",
        image: "ecodemedivh"
    },
    { 
        name: "Troggzor, o Aterrador", 
        attack: 6, 
        defense: 6, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "troggzoroaterrador"
    },
    { 
        name: "Tocha", 
        attack: 5, 
        defense: 7, 
        cost: 6, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra peca sobressalente", 
        class: "neutro", 
        collection: "gvg",
        image: "tocha"
    },
    { 
        name: "Técnico da Vila da Gambiarra", 
        attack: 3, 
        defense: 3, 
        cost: 3, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra peca sobressalente", 
        class: "neutro", 
        collection: "gvg",
        image: "tecnicodaviladagambiarra"
    },
    { 
        name: "Boneco-alvo", 
        attack: 0, 
        defense: 2, 
        cost: 0, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "provocar", 
        class: "neutro", 
        collection: "gvg",
        image: "bonecoalvo"
    },
    { 
        name: "Trogg Lascapedra", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "trogglascapedra"
    },
    { 
        name: "Tanque Aranha", 
        attack: 3, 
        defense: 4, 
        cost: 3, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "tanquearanha"
    },
    { 
        name: "Velho Retalhador do Sneed", 
        attack: 5, 
        defense: 7, 
        cost: 8, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro", 
        class: "neutro", 
        collection: "gvg",
        image: "velhoretalhadordosneed"
    },
    { 
        name: "Canhão do Navio", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "canhaodonavio"
    },
    { 
        name: "Velho Lobo do Mar", 
        attack: 7, 
        defense: 4, 
        cost: 5, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "pirata", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "velholobodomar"
    },
    { 
        name: "Recombobulador", 
        attack: 3, 
        defense: 2, 
        cost: 2, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "recombobulador"
    },
    { 
        name: "Pisa-poças", 
        attack: 3, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "murloc", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "pisapocas"
    },
    { 
        name: "Golem Celeste Guiado", 
        attack: 6, 
        defense: 4, 
        cost: 6, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro", 
        class: "neutro", 
        collection: "gvg",
        image: "golemcelesteguiado"
    },
    { 
        name: "Retalhador Guiado", 
        attack: 4, 
        defense: 3, 
        cost: 4, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro", 
        class: "neutro", 
        collection: "gvg",
        image: "retalhadorguiado"
    },
    { 
        name: "Brutamontes Ogro", 
        attack: 4, 
        defense: 4, 
        cost: 3, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "brutamontesogro"
    },
    { 
        name: "Mogor, o Ogro", 
        attack: 7, 
        defense: 6, 
        cost: 6, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "mogoroogro"
    },
    { 
        name: "Cabeça de Mimiron", 
        attack: 4, 
        defense: 5, 
        cost: 5, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "cabecademimiron"
    },
    { 
        name: "Minimago", 
        attack: 4, 
        defense: 1, 
        cost: 4, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "furtividade dano magico", 
        class: "neutro", 
        collection: "gvg",
        image: "minimago"
    },
    { 
        name: "Micromáquina", 
        attack: 1, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "micromaquina"
    },
    { 
        name: "Mecangenheiro Termaplugue", 
        attack: 9, 
        defense: 7, 
        cost: 9, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "mecangenheirotermaplugue"
    },
    { 
        name: "Yeti Mecânico", 
        attack: 4, 
        defense: 5, 
        cost: 4, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro peca sobressalente", 
        class: "neutro", 
        collection: "gvg",
        image: "yetimecanico"
    },
    { 
        name: "Mecano-traslador", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "mecanotraslador"
    },
    { 
        name: "Bombardeiro Muito Louco", 
        attack: 5, 
        defense: 4, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "bombardeiromuitolouco"
    },
    { 
        name: "Exorcistinha", 
        attack: 2, 
        defense: 3, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "provocar grito de guerra ultimo suspiro", 
        class: "neutro", 
        collection: "gvg",
        image: "exorcistinha"
    },
    { 
        name: "Moa Perdida", 
        attack: 5, 
        defense: 4, 
        cost: 4, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "fera", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "moaperdida"
    },
    { 
        name: "Sucatatron", 
        attack: 1, 
        defense: 5, 
        cost: 5, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "sucatatron"
    },
    { 
        name: "Mística de Kezan", 
        attack: 4, 
        defense: 3, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra segredo", 
        class: "neutro", 
        collection: "gvg",
        image: "misticadekezan"
    },
    { 
        name: "Jarbas", 
        attack: 1, 
        defense: 4, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "jarbas"
    },
    { 
        name: "Hobgoblin", 
        attack: 2, 
        defense: 3, 
        cost: 3, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "hobgoblin"
    },
    { 
        name: "Iluminador", 
        attack: 2, 
        defense: 4, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "segredo", 
        class: "neutro", 
        collection: "gvg",
        image: "iluminador"
    },
    { 
        name: "Rosarães Guima", 
        attack: 6, 
        defense: 3, 
        cost: 5, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "rosaraesguima"
    },
    { 
        name: "Sapador Goblin", 
        attack: 2, 
        defense: 4, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "sapadorgoblin"
    },
    { 
        name: "Infantaria de Gnomeregan", 
        attack: 1, 
        defense: 4, 
        cost: 3, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "investida provocar", 
        class: "neutro", 
        collection: "gvg",
        image: "infantariadegnomeregan"
    },
    { 
        name: "Experimentador Gnômico", 
        attack: 3, 
        defense: 2, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "experimentadorgnomico"
    },
    { 
        name: "Espreitador Guelblin", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "furtividade", 
        class: "neutro", 
        collection: "gvg",
        image: "espreitadorguelblin"
    },
    { 
        name: "Gasganete", 
        attack: 3, 
        defense: 6, 
        cost: 6, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "gasganete"
    },
    { 
        name: "Tanque de Força MÁX", 
        attack: 7, 
        defense: 7, 
        cost: 8, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "escudo divino", 
        class: "neutro", 
        collection: "gvg",
        image: "tanquedeforcamax"
    },
    { 
        name: "Ceifador de Inimigos 4000", 
        attack: 6, 
        defense: 9, 
        cost: 8, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "ceifadordeinimigos4000"
    },
    { 
        name: "Máquina Voadora", 
        attack: 1, 
        defense: 4, 
        cost: 3, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "furia dos ventos", 
        class: "neutro", 
        collection: "gvg",
        image: "maquinavoadora"
    },
    { 
        name: "Aníquilus", 
        attack: 8, 
        defense: 8, 
        cost: 5, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "aniquilus"
    },
    { 
        name: "Ovelha Explosiva", 
        attack: 1, 
        defense: 1, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro", 
        class: "neutro", 
        collection: "gvg",
        image: "ovelhaexplosiva"
    },
    { 
        name: "Mecanoide Aprimorador", 
        attack: 3, 
        defense: 2, 
        cost: 4, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "grito de guerra furia dos ventos provocar escudo divino", 
        class: "neutro", 
        collection: "gvg",
        image: "mecanoideaprimorador"
    },
    { 
        name: "Dr. Cabum", 
        attack: 7, 
        defense: 7, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "drcabum"
    },
    { 
        name: "Mestre da Engrenagem", 
        attack: 1, 
        defense: 2, 
        cost: 1, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "mestredaengrenagem"
    },
    { 
        name: "Gnomo de Corda", 
        attack: 2, 
        defense: 1, 
        cost: 1, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "ultimo suspiro peca sobressalente", 
        class: "neutro", 
        collection: "gvg",
        image: "gnomodecorda"
    },
    { 
        name: "Gigante de Corda", 
        attack: 8, 
        defense: 8, 
        cost: 12, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "gigantedecorda"
    },
    { 
        name: "Trogg Pedraqueixo Parrudo", 
        attack: 3, 
        defense: 5, 
        cost: 4, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "neutro", 
        collection: "gvg",
        image: "troggpedraqueixoparrudo"
    },
    { 
        name: "Taca-bomba", 
        attack: 3, 
        defense: 3, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "tacabomba"
    },
    { 
        name: "Blingtron 3000", 
        attack: 3, 
        defense: 4, 
        cost: 5, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "blingtron3000"
    },
    { 
        name: "Nulificador Arcano X-21", 
        attack: 2, 
        defense: 5, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "provocar", 
        class: "neutro", 
        collection: "gvg",
        image: "nulificadorarcanox21"
    },
    { 
        name: "Azucrinatron", 
        attack: 1, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "provocar escudo divino", 
        class: "neutro", 
        collection: "gvg",
        image: "azucrinatron"
    },
    { 
        name: "Robô de Cura Vintage", 
        attack: 3, 
        defense: 3, 
        cost: 5, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "grito de guerra", 
        class: "neutro", 
        collection: "gvg",
        image: "robodecuravintage"
    },
    { 
        name: "Minirrobô Blindado", 
        attack: 2, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "escudo divino", 
        class: "paladino", 
        collection: "gvg",
        image: "minirroboblindado"
    },
    { 
        name: "Selo da Luz", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "paladino", 
        collection: "gvg",
        image: "selodaluz"
    },
    { 
        name: "Purificador Escarlate", 
        attack: 4, 
        defense: 3, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra ultimo suspiro", 
        class: "paladino", 
        collection: "gvg",
        image: "purificadorescarlate"
    },
    { 
        name: "Intendente", 
        attack: 2, 
        defense: 5, 
        cost: 5, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "paladino", 
        collection: "gvg",
        image: "intendente"
    },
    { 
        name: "Preparação de Batalha", 
        attack: 0, 
        defense: 0, 
        cost: 3, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "paladino", 
        collection: "gvg",
        image: "preparacaodebatalha"
    },
    { 
        name: "Engrenomalho", 
        attack: 2, 
        defense: 3, 
        cost: 3, 
        rarity: "epico", 
        type: "arma", 
        especialType: "nenhum", 
        hability: "grito de guerra escudo divino provocar", 
        class: "paladino", 
        collection: "gvg",
        image: "engrenomalho"
    },
    { 
        name: "Guardião de Cobalto", 
        attack: 6, 
        defense: 3, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "mecanoide", 
        hability: "escudo divino", 
        class: "paladino", 
        collection: "gvg",
        image: "guardiaodecobalto"
    },
    { 
        name: "Bolvar Fordragon", 
        attack: 1, 
        defense: 7, 
        cost: 5, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "nenhum", 
        class: "paladino", 
        collection: "gvg",
        image: "bolvarfordragon"
    },
    { 
        name: "Vol'jin", 
        attack: 6, 
        defense: 2, 
        cost: 5, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: "nenhum", 
        hability: "grito de guerra", 
        class: "sarcedote", 
        collection: "gvg",
        image: "voljin"
    },
    { 
        name: "Escolhido de Velen", 
        attack: 0, 
        defense: 0, 
        cost: 3, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: "nenhum", 
        hability: "dano magico", 
        class: "sarcedote", 
        collection: "gvg",
        image: "escolhidodevelen"
    },
    { 
        name: "Robô de Reparos Aprimorado", 
        attack: 5, 
        defense: 5, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "grito de guerra", 
        class: "sarcedote", 
        collection: "gvg",
        image: "robodereparosaprimorado"
    },
    { 
        name: "Encolhista", 
        attack: 3, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: ",comum", 
        hability: "grito de guerra", 
        class: "sarcedote", 
        collection: "gvg",
        image: "encolhista"
    },
    { 
        name: "Boxeador da Sombra", 
        attack: 2, 
        defense: 3, 
        cost: 2, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "sarcedote", 
        collection: "gvg",
        image: "boxeadordasombra"
    },
    { 
        name: "Bombardeiro das Sombras", 
        attack: 2, 
        defense: 1, 
        cost: 1, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: ",nenhum", 
        hability: "grito de guerra", 
        class: "sarcedote", 
        collection: "gvg",
        image: "bombardeirodassombras"
    },
    { 
        name: "Luz dos Naarus", 
        attack: 0, 
        defense: 0, 
        cost: 1, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "sarcedote", 
        collection: "gvg",
        image: "luzdosnaarus"
    },
    { 
        name: "Bomba Luminosa", 
        attack: 0, 
        defense: 0, 
        cost: 6, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "sarcedote", 
        collection: "gvg",
        image: "bombaluminosa"
    },
    { 
        name: "Príncipe Mercador Gallywix", 
        attack: 5, 
        defense: 8, 
        cost: 6, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "ladino", 
        collection: "gvg",
        image: "principemercadorgallywix"
    },
    { 
        name: "Óleo de Arma do Faz-tudo", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "combo", 
        class: "ladino", 
        collection: "gvg",
        image: "oleodearmadofaztudo"
    },
    { 
        name: "Sabotagem", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "combo", 
        class: "ladino", 
        collection: "gvg",
        image: "sabotagem"
    },
    { 
        name: "Caolho Trapaceiro", 
        attack: 4, 
        defense: 1, 
        cost: 2, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",pirata", 
        hability: "furtividade", 
        class: "ladino", 
        collection: "gvg",
        image: "caolhotrapaceiro"
    },
    { 
        name: "Ogro Ninja", 
        attack: 6, 
        defense: 6, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",nenhum", 
        hability: "furtividade", 
        class: "ladino", 
        collection: "gvg",
        image: "ogroninja"
    },
    { 
        name: "Sensei de Ferro", 
        attack: 2, 
        defense: 2, 
        cost: 3, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "ladino", 
        collection: "gvg",
        image: "senseideferro"
    },
    { 
        name: "Autobarbeiro Goblínico", 
        attack: 3, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "grito de guerra", 
        class: "ladino", 
        collection: "gvg",
        image: "autobarbeirogoblinico"
    },
    { 
        name: "Chave do mestre da Engrenagem", 
        attack: 1, 
        defense: 3, 
        cost: 3, 
        rarity: "epico", 
        type: "arma", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "ladino", 
        collection: "gvg",
        image: "chavedomestredaengrenagem"
    },
    { 
        name: "Fulminatron Giratório", 
        attack: 3, 
        defense: 2, 
        cost: 2, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "furia dos ventos", 
        class: "xama", 
        collection: "gvg",
        image: "fulminatrongiratorio"
    },
    { 
        name: "Totem de Vitalidade", 
        attack: 0, 
        defense: 3, 
        cost: 2, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: "totem", 
        hability: "nenhum", 
        class: "xama", 
        collection: "gvg",
        image: "totemdevitalidade"
    },
    { 
        name: "Andarilho Espiritual Pinarena", 
        attack: 2, 
        defense: 5, 
        cost: 4, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: ",murloc", 
        hability: "sobrecarga", 
        class: "xama", 
        collection: "gvg",
        image: "andarilhoespiritualpinarena"
    },
    { 
        name: "Maça do Poder", 
        attack: 3, 
        defense: 2, 
        cost: 3, 
        rarity: "raro", 
        type: "arma", 
        especialType: ",nenhum", 
        hability: "ultimo suspiro", 
        class: "xama", 
        collection: "gvg",
        image: "macadopoder"
    },
    { 
        name: "Neptulon", 
        attack: 7, 
        defense: 7, 
        cost: 7, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: ",elemental", 
        hability: "grito de guerra sobrecarga", 
        class: "xama", 
        collection: "gvg",
        image: "neptulon"
    },
    { 
        name: "Xamã Dunamalho", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "furia dos ventos sobrecarga", 
        class: "xama", 
        collection: "gvg",
        image: "xamadunamalho"
    },
    { 
        name: "Estalar", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "sobrecarga", 
        class: "xama", 
        collection: "gvg",
        image: "estalar"
    },
    { 
        name: "Chamado do Ancestral", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "xama", 
        collection: "gvg",
        image: "chamadodoancestral"
    },
    { 
        name: "Senhora da Dor", 
        attack: 1, 
        defense: 4, 
        cost: 2, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",demonio", 
        hability: "roubar vida", 
        class: "bruxo", 
        collection: "gvg",
        image: "senhoradador"
    },
    { 
        name: "Mal'Ganis", 
        attack: 9, 
        defense: 7, 
        cost: 9, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: ",demonio", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "malganis"
    },
    { 
        name: "Implosão de Diabrete", 
        attack: 0, 
        defense: 0, 
        cost: 4, 
        rarity: "raro", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "implosaodediabrete"
    },
    { 
        name: "Observador Flutuante", 
        attack: 4, 
        defense: 4, 
        cost: 5, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: ",demonio", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "observadorflutuante"
    },
    { 
        name: "Canhão Vil", 
        attack: 3, 
        defense: 5, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "canhaovil"
    },
    { 
        name: "Coração Demoníaco", 
        attack: 0, 
        defense: 0, 
        cost: 5, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "coracaodemoniaco"
    },
    { 
        name: "Bomba Negra", 
        attack: 0, 
        defense: 0, 
        cost: 2, 
        rarity: "comum", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "bombanegra"
    },
    { 
        name: "Golem Ânima", 
        attack: 9, 
        defense: 9, 
        cost: 6, 
        rarity: "epico", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "bruxo", 
        collection: "gvg",
        image: "golemanima"
    },
    { 
        name: "Guerrobô", 
        attack: 1, 
        defense: 3, 
        cost: 1, 
        rarity: "comum", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "guerreiro", 
        collection: "gvg",
        image: "guerrobo"
    },
    { 
        name: "Máquina de Cerco", 
        attack: 5, 
        defense: 5, 
        cost: 5, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "nenhum", 
        class: "guerreiro", 
        collection: "gvg",
        image: "maquinadecerco"
    },
    { 
        name: "Dama Escudeira", 
        attack: 5, 
        defense: 5, 
        cost: 6, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",nenhum", 
        hability: "grito de guerra", 
        class: "guerreiro", 
        collection: "gvg",
        image: "damaescudeira"
    },
    { 
        name: "Calhambeque Vai-no-tranco", 
        attack: 2, 
        defense: 5, 
        cost: 4, 
        rarity: "raro", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "grito de guerra", 
        class: "guerreiro", 
        collection: "gvg",
        image: "calhambequevainotranco"
    },
    { 
        name: "Guerramalho Ôgrico", 
        attack: 4, 
        defense: 2, 
        cost: 3, 
        rarity: "comum", 
        type: "arma", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "guerreiro", 
        collection: "gvg",
        image: "guerramalhoogrico"
    },
    { 
        name: "Jaganata de Ferro", 
        attack: 6, 
        defense: 5, 
        cost: 6, 
        rarity: "lendario", 
        type: "lacaio", 
        especialType: ",mecanoide", 
        hability: "grito de guerra", 
        class: "guerreiro", 
        collection: "gvg",
        image: "jaganatadeferro"
    },
    { 
        name: "Esmagar", 
        attack: 0, 
        defense: 0, 
        cost: 7, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "guerreiro", 
        collection: "gvg",
        image: "esmagar"
    },
    { 
        name: "Lâmina Quicante", 
        attack: 0, 
        defense: 0, 
        cost: 3, 
        rarity: "epico", 
        type: "feitiço", 
        especialType: ",nenhum", 
        hability: "nenhum", 
        class: "guerreiro", 
        collection: "gvg",
        image: "laminaquicante"
    }
]


// FUNÇÃO COM OS FILTROS DE PESQUISA

function search(biblioteca, filtro, valor){
    let result = []
    switch (filtro) {
        case "add":
        case "rarity":
            result = biblioteca.filter(x => x.rarity === valor)
            break
        case "cost":
            result = biblioteca.filter(x => x.cost === valor)
            break
        case "attack":
            result = biblioteca.filter(x => x.attack === valor)
            break;
        case "defense":
            result = biblioteca.filter(x => x.defense === valor)
            break
        case "type":
            result = biblioteca.filter(x => x.type === valor)
            break
        case "class":
            result = biblioteca.filter(x => x.class === valor)
            break
        case "collection":
            result = biblioteca.filter(x => x.collection === valor)
            break
        case "search":
            result = biblioteca.filter(x => x.name === valor, x.hability === valor, x.especialType === valor, x.type === valor)
            break
        default:
            break;
    }
    return cardsHTML(result)
}

// FUNÇÃO PARA GERAR A ESTRUTURA HTML DE CARDS DE ACORDO COM O FILTRO DE PESQUISA 

function cardsHTML(vetorObjetos){
    let previa = vetorObjetos
    let result = ''
    for(let elemento of previa) {
        result += `    <div class="card ${elemento.rarity}">\n        <img src="img/${elemento.collection}/${elemento.image}.png">\n        <div class="shadow"></div>\n    </div>\n`
    }
    return result
}

// FUNÇÃO PARA GERAR UMA LISTA COM OS DADOS DE CADA OBJETO

function vetorCards(biblioteca){
    let previa = biblioteca
    let result = '['
    for(let elemento of previa){
        result += `["${elemento.name}",${elemento.cost},${elemento.attack},${elemento.defense},"${elemento.rarity}"],`
    }
    result += ']'
    return result
}

/* FUNÇÂO PARA ADICIONAR ELEMENTOS AO HTML */

function adicionar(identificador) {
    var cards = document.getElementById(identificador).value;
    var lista = search(library,"class",cards);

    document.getElementById("cards").innerHTML = lista;
}
